trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: 67

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      inputs:
#        containerRegistry: 'Docker hub connection'
#        repository: 'tbyuvaraaj/greeting-app-3'
#        command: 'buildAndPush'
#        Dockerfile: '**/Dockerfile'
#        tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
        

- stage: Deploy
  displayName: Deploy to K8S
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps: 
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(Systems.ArtifactsDirectory)'


